name: Create PR

on:
  workflow_dispatch:

jobs:
  create-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create a pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Configure"
          git config --global user.email "michalina.cienciala@akena.co"
          git config --global user.name "Michalina Cienciala"
          echo "Checkout"
          git checkout auto-update-api-docs-3 || git checkout -b auto-update-api-docs-3
          # echo "Pull"
          # git pull
          echo "Edit"
          date > newfile.txt
          echo "Add"                                                
          git add -A
          echo "Commit"
          git commit -m "Update docs"
          echo "Push"
          git push --set-upstream origin HEAD:auto-update-api-docs-3
          echo "PR"
          hub pull-request --base main --message "Update Solidity API docs" # --reviewer [...] --labels [...]
