name: Test retry

on:
  push:
  workflow_dispatch:

jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    outputs:
      job_id_url: ${{ steps.jobs.outputs.html_url }}
    steps:
      - name: Step that fails randomly
        run: |
          exit $((RANDOM % 2))
          echo $?

  trigger_rerun:
    name: Trigger rerun of ${{ github.run_id }}
    if: ${{ failure() }} # exeutes job if ancestor job have failed
    needs: randomly-failing-job
    runs-on: ubuntu-latest
    steps:
      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.RERUN_TOKEN }}
      #     repository: michalinacienciala/experimental
      #     event-type: my-event
      #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      - name: "Trigger run of `Retry` workflow"
        shell: pwsh
        env:
          # GITHUB_TOKEN with actions: write will NOT work
          # PAT Token must have workflow scope
          GH_CLI_TOKEN: ${{ secrets.RERUN_TOKEN_CLASSIC }}
        run: |
          echo "Running gh auth login..."
          $env:GH_CLI_TOKEN | gh auth login --with-token
          if(!$?) { exit 1 }
          echo "Triggering rerun"
          echo "
          gh workflow run rerun.yml
            --raw-field runId=$env:GITHUB_RUN_ID
            --repo $env:GITHUB_REPOSITORY
          "
          gh workflow run rerun.yml `
            --raw-field runId=$env:GITHUB_RUN_ID `
            --repo $env:GITHUB_REPOSITORY
          if(!$?) { exit 1 }