name: Retry failing job

on:
  push:
  workflow_dispatch:

jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    outputs:
      job_id_url: ${{ steps.jobs.outputs.html_url }}
    steps:
      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: randomly-failing-job

      # - name: Output Current Job Log URL
      #   run: echo "job-id=${{ steps.jobs.outputs.html_url }}

      - name: Step that fails randomly
        run: |
          exit $((RANDOM % 2))
          echo $?

  retry-job:
    runs-on: ubuntu-latest
    if: ${{ failure() }} # exeutes job if ancestor job have failed
    needs: randomly-failing-job
    steps:
      # - name: Extract workflow id from job URL
      #   id: get-workflow-id
      #   run: |
      #     echo ${{needs.randomly-failing-job.outputs.job_id_url}} | sed -n "s/^.*\/\([0-9]*\)\/.*$/\1/p"
      #     echo "workflow_id=$(!!)"  >> $GITHUB_OUTPUT

      # - name: Extract workflow id from job URL
      #   id: get-workflow-id
      #   run: |
      #     echo workflow_id = ${{needs.randomly-failing-job.outputs.job_id_url}} | sed -n "s/^.*\/\([0-9]*\)\/.*$/\1/p" >> $GITHUB_OUTPUT

      # - name: Rerun failing jobs in workflow
      #   continue-on-error: true
      #   run: |
      #     curl \
      #       -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.RERUN_TOKEN }}"\
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/michalinacienciala/experimental/actions/runs/${{ steps.get-workflow-id.outputs.workflow_id }}/rerun-failed-jobs
      - name: Rerun failing jobs in workflow
        continue-on-error: true
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.RERUN_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/michalinacienciala/experimental/actions/runs/$(echo ${{needs.randomly-failing-job.outputs.job_id_url}} | sed -n "s/^.*\/\([0-9]*\)\/.*$/\1/p")/rerun-failed-jobs
