name: Retry failing job

on:
  push:
  workflow_dispatch:

jobs:
  # randomly-failing-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get Current Job Log URL
  #       uses: Tiryoh/gha-jobid-action@v0
  #       id: jobs
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         job_name: randomly-failing-job

  #     - name: Output Current Job Log URL
  #       run: echo ${{ steps.jobs.outputs.html_url }}

  #     - name: Step that fails randomly
  #       run: |
  #         return $((RANDOM % 2))
  #         echo $?

  retry-job:
    runs-on: ubuntu-latest
    steps:
      - name: Rerun job
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.RERUN_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/michalinacienciala/experimental/actions/runs/4037242633/jobs/6940401675/rerun
  