name: Update staging and production environments

on:
  push:
    branches:
      - stage-live
  workflow_dispatch:

jobs:
    sync-main-to-stage-live:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Open/update a PR from `main` to `stage-live`
            id: pull  
            uses: tretuna/sync-branches@3428e61731dfc1b0c92e574a89f612c37340cad9
            with:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              FROM_BRANCH: "main"
              TO_BRANCH: "stage-live"
              PULL_REQUEST_TITLE: "🪄 [QA] Update stage environments"
              PULL_REQUEST_BODY: >
                This is a pull request that upon merging will update stage environments with recent `main` changes.\n
                The environments that will be updated:\n
                * Stage live: https://stage-live--taho-development.netlify.app/
                * Stage fork: https://stage-fork--taho-development.netlify.app/
              LABELS: '["deployment2"]'
          - uses: studroid/label-pr-or-issue-action@v1
            with:
              pr-or-issue-number: ${{ steps.pull.outputs.PULL_REQUEST_NUMBER }}
              label: "⚙️ deployment"
