name: Update staging and production environments

on:
  push:
    branches:
      - stage-live

jobs:
  sync-stage-live-to-stage-fork:
    if: github.ref == 'refs/heads/stage-live'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sync `stage-fork` with `stage-live`
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git checkout stage-fork
          git merge origin/stage-live
          git push origin stage-fork
  
